# Copyright (C) 2014-2015 Fabien Parent. All rights reserved.
# Author: Fabien Parent <parent.f@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-y += stm32f4-lowio.o
obj-$(CONFIG_BOARD_ARA_SVC_BDB1B) += board-bdb1b.o
obj-$(CONFIG_BOARD_ARA_SVC_BDB2) += board-bdb2.o
obj-$(CONFIG_BOARD_ARA_SVC_SDB) += board-sdb.o
obj-y += gpio.o
obj-y += rcc.o
