# Copyright (C) 2014-2015 Fabien Parent. All rights reserved.
# Author: Fabien Parent <parent.f@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-y += core.o
obj-$(CONFIG_UNIPRO_TSB) += unipro-tsb-es2.o
obj-$(CONFIG_UNIPRO_TSB) += unipro-tsb-es2-mphy-fixups.o
