# Copyright (C) 2014-2015 Fabien Parent. All rights reserved.
# Author: Fabien Parent <parent.f@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-$(CONFIG_GPIO) += core.o
obj-$(CONFIG_TCA6408) += tca6408.o
obj-$(CONFIG_TCA64XX) += tca64xx.o
obj-$(CONFIG_STM32_GPIO) += stm32-gpio.o
