# Copyright (C) 2014-2015 Fabien Parent. All rights reserved.
# Author: Fabien Parent <parent.f@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

subdirs-y += common
subdirs-$(CONFIG_CPU_ARMV7M) += arm-v7m
subdirs-$(CONFIG_MACH_STELLARIS) += mach-stellaris
subdirs-$(CONFIG_MACH_TSB) += mach-tsb
subdirs-$(CONFIG_MACH_STM32) += mach-stm32
