# Copyright (C) 2014-2015 Fabien Parent. All rights reserved.
# Author: Fabien Parent <parent.f@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-y := main.o
obj-y += libc-support.o
obj-y += shell.o
obj-y += scheduler.o

ld-script-y += kernel.ld
