# Copyright (C) 2014-2015 Fabien Parent. All rights reserved.
# Author: Fabien Parent <parent.f@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

subdirs-$(CONFIG_USB_HOST) += host
subdirs-$(CONFIG_USB_DEVICE) += gadget
subdirs-$(CONFIG_USB_DWC2) += dwc2
subdirs-$(CONFIG_USB_CORE) += class
