#obj-y += ina230.o
obj-y += tsb_es2_mphy_fixups.o
obj-y += vreg.o
obj-y += interface.o
obj-y += up_debug.o
obj-y += tsb_switch.o
obj-y += svc.o
obj-y += tsb_switch_es1.o
obj-y += board-bdb1b.o

#CSRCS		= up_boot.c
#CSRCS		+= tsb_switch_es1.c
#CSRCS		+= tsb_switch_es2.c

#ifeq ($(CONFIG_ARCH_BOARD_ARA_BDB1B_SVC),y)
#CSRCS		+= board-bdb1b.c
#CSRCS		+= up_bdb_pm.c
#CSRCS       += up_adc.c up_spring_pm.c
#endif

#ifeq ($(CONFIG_ARCH_BOARD_ARA_BDB2A_SVC),y)
#CSRCS		+= board-bdb2a.c
#CSRCS		+= up_bdb_pm.c
#CSRCS       += up_adc.c up_spring_pm.c
#endif

