# Copyright (C) 2015 Fabien Parent. All rights reserved.
# Author: Fabien Parent <parent.f@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

LDFLAGS += -Lapps/libphabos -l:libphabos.elf 

obj-y += test.o
obj-y += interp.o
