# Copyright (C) 2015 Fabien Parent. All rights reserved.
# Author: Fabien Parent <parent.f@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-y += fs.o
obj-y += inode.o
obj-y += fd.o
obj-y += fs-user.o
obj-y += fs-libc.o
obj-y += ramfs.o
obj-y += devfs.o
obj-$(CONFIG_BINFS) += binfs.o
obj-$(CONFIG_PROCFS) += procfs.o
