# Copyright (C) 2014-2015 Fabien Parent. All rights reserved.
# Author: Fabien Parent <parent.f@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

subdirs-$(CONFIG_SERIAL) += serial
subdirs-$(CONFIG_I2C) += i2c
subdirs-$(CONFIG_USB) += usb
subdirs-$(CONFIG_GPIO) += gpio
subdirs-$(CONFIG_GREYBUS) += greybus
subdirs-$(CONFIG_ARA_BACKPORT) += ara

obj-y += core.o
