# Copyright (C) 2014-2015 Fabien Parent. All rights reserved.
# Author: Fabien Parent <parent.f@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-y += core.o
obj-$(CONFIG_I2C_DW) += dw.o
obj-$(CONFIG_STM32_I2C) += stm32-i2c.o
