# Copyright (C) 2015 Fabien Parent. All rights reserved.
# Author: Fabien Parent <parent.f@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

obj-y += tty.o
obj-$(CONFIG_UART16550) += uart16550.o
obj-$(CONFIG_STM32_USART) += stm32-usart.o
