subdirs-$(CONFIG_MACH_TSB) += tsb
subdirs-$(CONFIG_APP_APBRIDGEA) += apbridgea
subdirs-$(CONFIG_APP_SVC) += svc
subdirs-$(CONFIG_APP_GREYBUS_UTILS) += greybus-utils

obj-$(CONFIG_APP_UNIPRO) += unipro.o
obj-$(CONFIG_APP_GPIO) += gpio.o
obj-$(CONFIG_APP_I2S) += i2s.o
obj-$(CONFIG_APP_GREYBUS_LOOPBACK) += gb-loopback.o
