subdirs-$(CONFIG_MACH_TSB) += tsb
subdirs-$(CONFIG_TSB_APB1) += apbridgea

obj-$(CONFIG_UNIPRO) += unipro.o
obj-$(CONFIG_GPIO) += gpio.o
obj-$(CONFIG_ARA_BACKPORT) += i2s.o
obj-$(CONFIG_GREYBUS_LOOPBACK) += gb-loopback.o
