# Copyright (C) 2015 Fabien Parent. All rights reserved.
# Author: Fabien Parent <parent.f@gmail.com>
#
# Provided under the three clause BSD license found in the LICENSE file.

CFLAGS += -Idrivers/greybus/

obj-y += svc.o
